[package]
name = "mcm-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
mcm-core = { path = "../crates/mcm-core" }
mcm-export = { path = "../crates/mcm-export" }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.4.1"
zip.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
